### ISSUE TITLE
Proyecto de Héctor Rodríguez Sosa y Sebastián Suárez Gómez

### ISSUE THREAD

**Issue by vekt0R-HUB** [matcom/domino#10]
Modifique las líneas siguientes con los detalles relevantes:

### Equipo

- C211, Hector Miguel Rodríguez Sosa (@vekt0R-HUB)
- C211, Sebastián Suárez Gómez (@Scorpion-Ceeb)

## Proyecto

- **Repositorio**: <https://github.com/vekt0R-HUB/2nd-Year-Project>
- **Proyecto**: <https://github.com/vekt0R-HUB/2nd-Year-Project/blob/master/Report.pdf>

## Checklist

*(Esta lista es para el mentor. Hasta que no estén chequeados estos elementos no se procederá a la evaluación en persona.)*

### Básicos

- [ ] El repositorio indicado existe y tiene un `Readme.md` no vacío.
- [ ] Los miembros del equipo tienen un usuario de Github válido.
- [ ] El proyecto puede ser ejecutado siguiendo las instrucciones del `Readme.md`.
- [ ] El reporte existe y tiene la longitud adecuada.

### Funcionalidades

- [ ] El proyecto permite configurar al menos 5 elementos relevantes de la mecánica del dominó.
- [ ] El proyecto contiene 2 implementaciones diferentes de cada elemento configurable.
- [ ] El proyecto permite personalizar las estrategias de los jugadores virtuales.
- [ ] El proyecto contiene al menos 3 implementaciones diferentes de jugadores virtuales.

### Ingeniería de Software

- [ ] Las estrategias de jugadores virtuales pueden combinarse con cualquier configuración del juego de forma transparente.
- [ ] La interfaz gráfica permite configurar el juego en toda la extensión que brinda la lógica.
- [ ] Las jerarquías de clases y demás abstracciones existentes son adecuadas para modelar el dominio.
- [ ] El código muestra una organización y estructura mantenible y extensible, respetando las buenas prácticas de la ingeniería de software.

### Documentación

- [ ] El reporte técnico explica de forma suficientemente detallada los pormenores del proyecto.
- [ ] Los nombres de clases, métodos y variables son descriptivos.
- [ ] Los comentarios son legibles y útiles para entender el funcionamiento del código.

## Revisión

**Fecha prevista:** 2020/XX/XX

### Comentarios

*(Para rellenar por el mentor)*

**Comment by e1Ru1o** [comment]
Por que la logica de si una ficha se puede poner en un tablero esta en la ficha y no en el tablero :thinking:? Pueden comentar razones por la cual se escogio este disenno?

**Comment by e1Ru1o** [comment]
Error al ejecutar los pasos de `Blazor`

Pasos seguidos:
1. `cd BlazorApp`
2. `dotnet restore`
    > Determining projects to restore... 
    > ... (omitted)
    > All projects are up-to-date for restore.
4. `dotnet watch run`
    > ... (initial logs omitted)
    > **dotnet watch 🚀 Started**
    > Unhandled exception. System.InvalidOperationException: Unable to configure HTTPS endpoint. No server certificate was specified, and the default developer certificate could not be found or is out of date.
    > To generate a developer certificate run 'dotnet dev-certs https'. To trust the certificate (Windows and macOS only) run 'dotnet dev-certs https --trust'.
    > For more information on configuring HTTPS see https://go.microsoft.com/fwlink/?linkid=848054.
    >    at Microsoft.AspNetCore.Hosting.ListenOptionsHttpsExtensions.UseHttps(ListenOptions listenOptions, Action 1 configureOptions)
    >    at Microsoft.AspNetCore.Hosting.ListenOptionsHttpsExtensions.UseHttps(ListenOptions listenOptions)
    >    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.AddressesStrategy.BindAsync(AddressBindContext context, CancellationToken cancellationToken)
    >    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindAsync(IEnumerable 1 listenOptions, AddressBindContext context, CancellationToken cancellationToken)
    >    at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerImpl.BindAsync(CancellationToken cancellationToken)
    >    at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerImpl.StartAsync[TContext](IHttpApplication 1 application, CancellationToken cancellationToken)
    >    at Microsoft.AspNetCore.Hosting.GenericWebHostService.StartAsync(CancellationToken cancellationToken)
    >    at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
    >    at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
    >    at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
    >    at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.Run(IHost host)
    >    at Microsoft.AspNetCore.Components.WebAssembly.DevServer.Program.Main(String[] args)
    > 
    > dotnet watch ❌ Exited with error code 134

**Comment by vekt0R-HUB** [comment]
La lógica de la ficha se escogió de esa forma porque parecía tener más sentido que la responsabilidad de la ficha fue la ficha en sí y de nadie más

En la aplicación de consola lo siguiente:
- Es verdad que hubiera faltado especificación en varias cosas 
- Pidió el rounder dos veces por un pequeño bug que pedía el rounder una vez y después un shuffler pero en realidad el encabezado en ambos decía rounder, un simple cambio de string
- Para salir simplemente esperar a q se juegue el juego completo y usar y si quiere seguir jugando o n si no, y si usa n se cierra automático

Con respecto a la aplicación de Blazor no sé por qué le está dando ese problema. Acabo de descargar el proyecto en otra carpeta, siguiendo todos los pasos puestos en el readme, y funciona perfectamente.

**Comment by e1Ru1o** [comment]
- Las fichas no deberian tener responsabilidad. Lo que se haga con una ficha depende de la logica del juego. Un mismo tipo de ficha puede utilizarse en diferentes juegos, en todos tener sentido pero utilizarse de manera diferente. 
- El problema de la app de blazor lo resolvi siguiendo la recomendacion del error que les comparti. La probe y no aporta mucho valor respecto a la aplicacion de consola dado que la informacion se muestra de la misma manera.
- Se hace complicado probar su juego dado que no hay como verlo paso a paso y el resultado final no es muy descriptivo

**Comment by vekt0R-HUB** [comment]
Se añadió una funcionalidad para el jugador humano en la aplicación de consola. Lamentablemente no tenemos tiempo para hacerlo de igual manera para la aplicación de blazor
